name: Test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      CARGO_TERM_COLOR: always
      REDIS_URL: redis://localhost:6379
      RUST_LOG: trace

    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Format
        run: cargo fmt --all --check

      - name: Test
        run: |
          cargo test --lib --no-default-features
          cargo nextest run --all-features --no-fail-fast

      - name: Lint
        run: cargo clippy --all-features --workspace --all-targets -- -D warnings

      - name: Benchmark
        run: cargo bench

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: |
          cargo publish -p oxana-macros || true
          cargo publish -p oxana || true
          cargo publish -p oxana-web || true
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
